// Ordered track list for bluetooth.wtf, extracted directly from the public
// playlist page (youtube.com/playlist?list=PLNQk18YUccs2R8_aqb6EgEDA5e-uACqWm)
// on 2026-08-15 — every id below is real, pulled from that
// page's DOM, never invented. Titles/artists are cleaned at authoring time with
// the same rules as the runtime fallback cleaner in player-ui.js (§7.2).
//
// This trades the "YouTube owns the tracklist" architecture for reliability —
// loading individual videos by id, rather than asking YouTube to resolve the
// full playlist server-side, survives the content-blocker conditions that broke
// playlist-mode loading in testing (see session notes). Re-run the scrape (or
// the real audit script once an API key exists) to add new songs; this list
// does not auto-update from the YouTube playlist anymore.
export const PLAYLIST = [
  { id: 'ADXL0nkkfak', title: "Bewafa", artist: "imrankhanworld" },
  { id: 'VyodL1mP8cc', title: "Brown Rang", artist: "Yo Yo Honey Singh" },
  { id: 'Njx_k6GeeHA', title: "Hiriye", artist: "Release" },
  { id: 'hifVLNuEJeA', title: "Dil Luteya", artist: "Jazzy B Records" },
  { id: 'nn59knX5n1w', title: "Falak Ijazat Full Song", artist: "T-Series" },
  { id: '49XkP7GWz3w', title: "ISHQ", artist: "Speed Records" },
  { id: '13uzQU0mfnM', title: "Yaar Bathere Alfaaz feat Yo Yo Honey Singh", artist: "Speed Records" },
  { id: 'uuCFRaFWjwY', title: "Imran Khan - Amplifier", artist: "imrankhanworld" },
  { id: 'xoWjZvAkD1M', title: "Amplifier", artist: "imrankhanworld" },
  { id: 'qRTG8uF2ES4', title: "Aaja We Mahiya", artist: "imrankhanworld" },
  { id: 'QwJjNysHVhM', title: "Ride It", artist: "jayseanworldwide" },
  { id: '86h_3HSoEkc', title: "Mann Bharryaa 2.0", artist: "B Praak" },
  { id: 'NJAv_7lHUIU', title: "Kesariya", artist: "Arijit Singh" },
  { id: 'MGCj07ThRAI', title: "Jaadui", artist: "Pritam" },
  { id: 'aG7MaqtWxT8', title: "Khuda Jaane", artist: "Vishal - Shekhar" },
  { id: '01HR1uP4kic', title: "Tune Jo Na Kaha", artist: "Mohit Chauhan" },
  { id: 'DGgz_C2rn68', title: "Dildaara", artist: "Vishal - Shekhar" },
  { id: 'YYy94KgojVA', title: "AYE MERI ZINDAGI", artist: "Shreya Ghoshal Official" },
  { id: 'ii9KLQoV78I', title: "Hawayein", artist: "Pritam" },
  { id: '1q65CU2JoXg', title: "Iktara", artist: "Amit Trivedi" },
  { id: 't9TAX7pSgGg', title: "Bana Sharabi", artist: "Tanishk Bagchi" },
  { id: 'DEatLVqGuTo', title: "Abhi Kuch Dino Se", artist: "Pritam" },
  { id: '6DIuKEWWEg8', title: "Hosanna", artist: "A. R. Rahman" },
  { id: 'SeSbwS34PgY', title: "TU HAI KI NAHI", artist: "Ankit Tiwari" },
  { id: 'eXkHvT--DBU', title: "Zaalima", artist: "Arijit Singh" },
  { id: 'nBcKS3dhe5U', title: "Love You Zindagi", artist: "Amit Trivedi" },
  { id: 'wR3r0NX1PJE', title: "O Sanam", artist: "Lucky Ali" },
  { id: 'AqVIQ9ymvM8', title: "Tum Ho", artist: "Mohit Chauhan" },
  { id: 'GpLj8f2CI00', title: "Sawaar Loon", artist: "Monali Thakur" },
  { id: 'ZzVyBV9cAXY', title: "Kahani", artist: "Pritam" },
  { id: 'p2lzwXkO2QE', title: "Phir Na Aisi Raat Aayegi", artist: "Pritam" },
  { id: '6XvyKlvl31o', title: "Manja", artist: "Amit Trivedi" },
  { id: '6NeVceQd6yI', title: "KAISE MUJHE", artist: "Benny Dayal" },
  { id: '7EfWkbQfnLg', title: "YE TUMHARI MERI BAATEIN", artist: "Dominique Cerejo" },
  { id: 'ooH9UqewI7A', title: "Bheegi Si Bhaagi Si", artist: "Pritam" },
  { id: '10OXPgsQcyY', title: "Kitni Haseen Hogi", artist: "Arijit Singh" },
  { id: 'Hqajq5jKX10', title: "Sapna Jahan", artist: "Ajay Gogavale" },
  { id: 'FCRUrHJW468', title: "SAFARNAMA", artist: "Lucky Ali" },
  { id: '-UU9J-LbfB8', title: "Samjhawan (Unplugged by Alia Bhatt)", artist: "Jawad Ahmad" },
  { id: 'VFft2ReLqlQ', title: "Naa Tere Bin", artist: "Altamash Faridi" },
  { id: 'FYQUIUGQSKA', title: "Pyaar Mein", artist: "Stebin Ben" },
  { id: 'Z_Pr3Z9jz8I', title: "Humdard", artist: "Arijit Singh" },
  { id: '2g-p76-r33I', title: "Zehnaseeb", artist: "Vishal - Shekhar" },
  { id: '4g0QivOeup0', title: "Khaabon Ke Parinday", artist: "Mohit Chauhan" },
  { id: 'aZ4qpbXuSwQ', title: "Mera Yaar", artist: "Shankar Ehsaan Loy" },
  { id: 'BEJKkdDdKmQ', title: "Journey Song", artist: "Anupam Roy" },
  { id: 'Zf3NV7DJolc', title: "Ki Kariye", artist: "Harrdy Sandhu" },
  { id: 'Wuyyk45NYlg', title: "Atak Gaya - Acoustic", artist: "Amit Trivedi" },
  { id: 'jUmKqnziT7k', title: "Chupke Chupke", artist: "R MUSIC by Rochak Kohli" },
  { id: 'oX6FJxwI7GE', title: "Barsaat Ka Mausam", artist: "Saaj Bhatt" },
  { id: 'Px4-yQRZu_U', title: "CHAAR KADAM", artist: "Singer Shaan" },
  { id: 'wzOWggEF0No', title: "Kaisi Hai Ye Rut", artist: "Srinivas" },
  { id: 'jZGyxQOQcd0', title: "Dekha Hazaro Dafaa", artist: "Arijit Singh" },
  { id: 'PEiFJAy_zsM', title: "Shubho Shubho", artist: "Altamash Faridi" },
  { id: 'HABOZiya_YM', title: "Ghalib Hona Hai", artist: "Sanjay Leela Bhansali" },
  { id: 'ZPoB5BKuzm8', title: "Rafu", artist: "Ronkini Gupta" },
  { id: 'EaaeuLFk5rg', title: "Tere Bin", artist: "Sonu Nigam" },
  { id: '6N6Bf_mO8d8', title: "Bolna (From \"Kapoor & Sons (Since 1921)\")", artist: "Tanishk Bagchi" },
  { id: 'kr8QADGWKAc', title: "Muskuraa Lena Tum", artist: "Palak Muchhal" },
  { id: 'ppSbDd0NjLE', title: "Phir Le Aya Dil (Redux)", artist: "Pritam" },
  { id: 'rIXN6mAvk1w', title: "Mangoge Na ?", artist: "ARJUNA" },
  { id: 'BA37wV6e7IE', title: "Malang Sajna", artist: "Sachet Tandon" },
  { id: 'GkJ_wZy0iB4', title: "Ve Kamleya", artist: "Pritam" },
  { id: 'zP9n2ZAS28Q', title: "Faasle", artist: "Aditya Rikhari" },
  { id: 'WKv07mnKVEE', title: "Kaise Hua", artist: "Vishal Mishra" },
  { id: 'qVbG2S3Av_w', title: "Saajna", artist: "MITRAZ" },
  { id: '_65_c-0ubCw', title: "Hona Tha Pyar", artist: "Atif Aslam" },
  { id: 'Io_Z3HxgJGs', title: "Jee Le Zaraa", artist: "Vishal Dadlani" },
  { id: 'zRKvLzLVIKQ', title: "Tera Zikr", artist: "DarshanRavalDZ" },
  { id: '7BFHPc3r9QA', title: "Ijazat", artist: "Falak Shabir" },
  { id: 'JIglHLx8zVY', title: "Ilzaam", artist: "Arjun Kanungo" },
  { id: 'cBLNAFozsBg', title: "Dil Na Jaaneya", artist: "Arijit Singh" },
  { id: 'Fi3GovijpWA', title: "Tere Bina", artist: "A. R. Rahman" },
  { id: '9Cp-hNvSWZs', title: "Maiyya Mainu", artist: "Sachet Tandon" },
  { id: '9TwPZYt33tI', title: "Kho Gaye Hum Kahan", artist: "Jasleen Royal" },
  { id: 'KptF_0yWr_Q', title: "SAWARE", artist: "Arijit Singh" },
  { id: '5qNxG3oJsag', title: "Chitta", artist: "Manan Bhardwaj" },
  { id: 'ggkFzE2236U', title: "Chidiya", artist: "Vilen" },
  { id: 'MQsxNpPjAPQ', title: "Alfaazo", artist: "MITRAZ" },
  { id: 'iY4x5QZcGZA', title: "Pehla Pyaar", artist: "Armaan Malik" },
  { id: 'GHTg-EzUr4M', title: "Aaftaab", artist: "The Local Train" },
  { id: 'sJ2cDsopCV4', title: "Nadiyon Sa", artist: "MITRAZ" },
  { id: 'NI1mPv82Rv0', title: "Kho Gaye", artist: "Release" },
  { id: 'Fn4RWAqsi_M', title: "Mar Jaayen", artist: "Atif Aslam" },
  { id: 'Zkqhiil2kSo', title: "Yeh Fitoor Mera", artist: "Arijit Singh" },
  { id: 'SHNMIFcwgI8', title: "Aaj Bhi", artist: "Vishal Mishra" },
  { id: 'Kh49Zqa84IE', title: "Gul", artist: "Anuv Jain" },
  { id: 'kBP3QFMUTnY', title: "Hoor", artist: "Atif Aslam" },
  { id: 'lW7Cl3Vrr6o', title: "Tu Rehti Hai", artist: "Aditya Rikhari" },
  { id: 'G1j28AYj9jA', title: "Mat Aazma Re", artist: "Pritam" },
  { id: 'jw1je6Mc-8Y', title: "Nazm Nazm", artist: "ARKO" },
  { id: 'S3KrTYMil8I', title: "Subah Se Shaam", artist: "Madhur Sharma" },
  { id: 'uwgAcLVaBW0', title: "Bandeya", artist: "Shaarib Toshi" },
  { id: '_TJZaE0FkKs', title: "DIL TO BACHCHA HAI", artist: "The Folk & Soul Studio" },
  { id: 'gOSM2dEqwsE', title: "Pehli Dafa", artist: "Atif Aslam" },
  { id: 'BOnxCtKA1VE', title: "Namo Namo", artist: "Amit Trivedi" },
  { id: 'dRhjpiF-FmI', title: "Awari", artist: "Adnan Dhool Official" },
  { id: 'FS7fbMl-h10', title: "Jo Bhi Main", artist: "Mohit Chauhan" },
  { id: 'R_T2uJX2r8A', title: "KINNA SONA", artist: "Sunil Kamath" },
];
